#!/usr/bin/env python3
"""Pack the Clippy frames the graveyard page uses out of clippy.js's sheet.

Dev-time only; the results (static/clippy.png, static/clippy.css,
static/favicon.ico) are committed. Reads map.png + agent.json from the omarchy-inappropriate-clippy
checkout (those come from clippy.js; Microsoft's artwork), keeps only the
cells that ANIMS touch, tiles them COLS wide, and writes one @keyframes per
animation that steps background-position through the straight frame path
(index + 1; clippy.js's random branching is not reproduced). Two copies of
each, -a and -b: a browser only restarts an animation when animation-name
changes, and the page alternates them so back-to-back quotes with the same
animation both play. Durations go out as --dur-<name> custom properties so
app.py never has to know them.

    scripts/build-sprite.py [path/to/assets/clippy]

Needs ImageMagick (magick, montage).
"""

import json
import pathlib
import subprocess
import sys
import tempfile

# Rest pose first so cell 0 is "him, doing nothing". Then everything a quote,
# a slap or the idle twitch can ask for. Adding one here is the whole job;
# QUOTES/SLAPPED in app.py may then use it.
ANIMS = ["RestPose", "IdleEyeBrowRaise", "Alert", "Wave", "Hearing_1", "GetAttention"]
IDLE = "IdleEyeBrowRaise"
IDLE_HOLD_MS = 7500  # rest this long, then the twitch, then round again
COLS = 12
W, H = 124, 93

DEFAULT_SRC = "~/Work/omarchy-inappropriate-clippy/assets/clippy"


def main():
    src = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else DEFAULT_SRC).expanduser()
    out = pathlib.Path(__file__).resolve().parent.parent / "static"
    out.mkdir(exist_ok=True)
    agent = json.loads((src / "agent.json").read_text())
    assert agent["framesize"] == [W, H], agent["framesize"]

    # Unique cells in first-use order; a path per animation as (cell, ms).
    cells = [(0, 0)]
    paths = {}
    for name in ANIMS:
        path = []
        for frame in agent["animations"][name]["frames"]:
            x, y = frame["images"][0]  # none of ANIMS has a hidden frame
            assert x % W == 0 and y % H == 0, (name, x, y)
            if (x, y) not in cells:
                cells.append((x, y))
            path.append((cells.index((x, y)), frame["duration"]))
        paths[name] = path

    # One magick call slices the whole sheet into tiles named by grid index,
    # then montage picks the ones we want.
    sheet_cols = 3348 // W
    with tempfile.TemporaryDirectory() as tmp:
        subprocess.run(
            ["magick", str(src / "map.png"), "-crop", f"{W}x{H}", "+repage", "+adjoin", f"{tmp}/t-%d.png"],
            check=True,
        )
        picks = [f"{tmp}/t-{(y // H) * sheet_cols + x // W}.png" for x, y in cells]
        subprocess.run(
            ["montage", *picks, "-tile", f"{COLS}x", "-geometry", f"{W}x{H}+0+0", "-background", "none", str(out / "clippy.png")],
            check=True,
        )
    subprocess.run(["magick", str(out / "clippy.png"), "-strip", str(out / "clippy.png")], check=True)

    # Favicon: cell 0 (the rest pose) trimmed to its bounding box, squared on
    # a transparent canvas, as one .ico holding 48, 32 and 16 px.
    subprocess.run(
        [
            "magick", str(out / "clippy.png"), "-crop", f"{W}x{H}+0+0", "+repage", "-trim", "+repage",
            "-background", "none", "-gravity", "center", "-extent", "%[fx:max(w,h)]x%[fx:max(w,h)]",
            "-define", "icon:auto-resize=48,32,16", str(out / "favicon.ico"),
        ],
        check=True,
    )

    def pos(cell):
        return f"{-(cell % COLS) * W}px {-(cell // COLS) * H}px"

    def keyframes(name, path, hold_ms=0):
        """Stops at cumulative time; consecutive same-cell frames merge. Ends on rest."""
        total = hold_ms + sum(ms for _, ms in path)
        stops, t, last = [], 0, None
        if hold_ms:
            stops.append((0, 0))
            last, t = 0, hold_ms
        for cell, ms in path:
            if cell != last:
                stops.append((t, cell))
                last = cell
            t += ms
        if last != 0:
            stops.append((t, 0))
        body = " ".join(f"{100 * at / total:.2f}% {{background-position: {pos(cell)}}}" for at, cell in stops)
        return total, f"@keyframes {name} {{ {body} }}"

    lines = [
        f"/* generated by scripts/build-sprite.py — do not edit. {len(cells)} cells of {W}x{H}, {COLS} per row,",
        "   from clippy.js's sheet via omarchy-inappropriate-clippy. Cell 0 is the rest pose. */",
    ]
    durs = {}
    for name in ANIMS:
        if name == "RestPose":
            continue
        durs[name], css = keyframes(f"{name}-a", paths[name])
        lines.append(css)
        lines.append(css.replace(f"{name}-a", f"{name}-b", 1))
    durs["idle"], css = keyframes("idle", paths[IDLE], IDLE_HOLD_MS)
    lines.append(css)
    lines.insert(2, ":root { " + " ".join(f"--dur-{n}: {ms}ms;" for n, ms in durs.items()) + " }")
    (out / "clippy.css").write_text("\n".join(lines) + "\n")

    rows = -(-len(cells) // COLS)
    print(f"{len(cells)} cells -> static/clippy.png ({COLS}x{rows}, {(out / 'clippy.png').stat().st_size // 1024} KB), static/clippy.css, static/favicon.ico")
    for n, ms in durs.items():
        print(f"  {n}: {ms} ms")


if __name__ == "__main__":
    main()
